#!/usr/bin/env bash
set -euo pipefail

TITLE="${1:-DRL-Based SFC Provisioning with Forecasting & Monitoring}"
OUT="diagram.puml"

if [[ ! -f "diagram.puml.template" ]]; then
  echo "diagram.puml.template not found" >&2
  exit 1
fi

{
  echo "' Generated by gen.sh"
  echo "!define TITLE \"${TITLE}\""
  grep -v '^!define TITLE ' diagram.puml.template
} > "$OUT"

echo "Wrote $OUT"

if command -v plantuml >/dev/null 2>&1; then
  plantuml "$OUT"
  echo "Rendered diagram to diagram.png (and/or diagram.svg)"
else
  echo "plantuml not found; skipped rendering. To render: plantuml $OUT"
fi
