param(
    [string]$Title = "DRL-Based SFC Provisioning with Forecasting & Monitoring"
)

$Template = "diagram.puml.template"
$Out = "diagram.puml"

if (-not (Test-Path $Template)) {
    Write-Error "$Template not found"
    exit 1
}

$lines = Get-Content $Template
$filtered = $lines | Where-Object { $_ -notmatch '^!define TITLE ' }

"' Generated by gen.ps1" | Out-File -FilePath $Out -Encoding utf8
("!define TITLE \"$Title\"") | Out-File -FilePath $Out -Append -Encoding utf8
$filtered | Out-File -FilePath $Out -Append -Encoding utf8

Write-Host "Wrote $Out"

$plantuml = Get-Command plantuml -ErrorAction SilentlyContinue
if ($plantuml) {
    & plantuml $Out
    Write-Host "Rendered diagram to diagram.png (and/or diagram.svg)"
} else {
    Write-Host "plantuml not found; skipped rendering. To render: plantuml $Out"
}
