global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - "vnf_rules.yml"

scrape_configs:
  # Prometheus self-scraping
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

